export const ERRORS = {
    EMAIL_ALREADY_REGISTERED: 1,
    USER_NAME_ALREADY_REGISTERED: 2,
    USER_NOT_FOUND: 3,
    PASSWORD_INCORRECT: 4,
    USER_INACTIVE: 5,
    INVALID_TOKEN: 6,
    INVALID_SESSION: 7,
    ERROR_UPLOAD_FILE: 8,
    ERROR_GET_FILE: 9,
    NOT_ACCESS_RESOURCE: 10
} as const